### PR TITLE
autpost timer

### PR DESCRIPTION
**Pull request by takipsizad**
## Proposed Changes
added autopost timer

  -
  -
  -

### CODE REVIEW

**Comment by takipsizad** [comment]
lol

**Review by shivaco — CHANGES_REQUESTED** [review]
1. Stick to the specific naming conventions of the Python SDK regarding autopost, which is snake_case. In this case, rename `autoposttimer` to `autopost_timer`;
2. Please stick to proper code formatting;
3. Feel free to refer to `self.autoposttimer` (see point 2) instead of adding additional parameters;
4. Please document this in the DBLClient docstring. If you need further help with this, feel free to contact me.

**Comment by takipsizad** [comment]
ok

**Comment by ChillFish8** [comment]
Man, actually test that what you're changing works before committing like jesus dude.

**Comment by shivaco** [comment]
Please get a hang of OOP in Python and learn how scopes work. Until then, please refrain from creating pull requests.

I will implement this manually myself soon. Thank you for the suggestion.

**Comment by takipsizad** [comment]
> 
> 
> Please get a hang of OOP in Python and learn how scopes work. Until then, please refrain from creating pull requests like this.
> 
> I will implement this manually myself soon. Thank you for the suggestion.

ok

**Comment by takipsizad** [comment]
tbh i dont see whats wrong with it ?

**Comment by shivaco** [comment]
> 
> 
> tbh i dont see whats wrong with it ?

You failed to resolve multiple requested changes on top of not having the necessary knowledge to actually write working/formatted code. The mistakes in the code you have made are by far very basic when it comes to dealing with scopes and Python OOP generally.

**Comment by takipsizad** [comment]
ok

**Pull request closed without merging**
